In [121]:
import pandas as pd
import numpy as np
import sklearn

In [122]:
melbourne_data = pd.read_csv("melb_data.csv")
melbourne_data.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0

In [123]:
melbourne_data.describe() # summary

,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
count,13580.000000,1.358000e+04,13580.000000,13580.000000,13580.000000,13580.000000,13518.000000,13580.000000,7130.000000,8205.000000,13580.000000,13580.000000,13580.000000
mean,2.937997,1.075684e+06,10.137776,3105.301915,2.914728,1.534242,1.610075,558.416127,151.967650,1964.684217,-37.809203,144.995216,7454.417378
std,0.955748,6.393107e+05,5.868725,90.676964,0.965921,0.691712,0.962634,3990.669241,541.014538,37.273762,0.079260,0.103916,4378.581772
min,1.000000,8.500000e+04,0.000000,3000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1196.000000,-38.182550,144.431810,249.000000
25%,2.000000,6.500000e+05,6.100000,3044.000000,2.000000,1.000000,1.000000,177.000000,93.000000,1940.000000,-37.856822,144.929600,4380.000000
50%,3.000000,9.030000e+05,9.200000,3084.000000,3.000000,1.000000,2.000000,440.000000,126.000000,1970.000000,-37.802355,145.000100,6555.000000
75%,3.000000,1.330000e+06,13.000000,3148.000000,3.000000,2.000000,2.000000,651.000000,174.000000,1999.000000,-37.756400,145.058305,10331.000000
max,10.000000,9.000000e+06,48.100000,3977.000000,20.000000,8.000000,10.000000,433014.000000,44515.000000,2018.000000,-37.408530,145.526350,21650.000000

In [124]:
melbourne_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         13580 non-null  object
 1   Address        13580 non-null  object
 2   Rooms          13580 non-null  int64
 3   Type           13580 non-null  object
 4   Price          13580 non-null  float64
 5   Method         13580 non-null  object
 6   SellerG        13580 non-null  object
 7   Date           13580 non-null  object
 8   Distance       13580 non-null  float64
 9   Postcode       13580 non-null  float64
 10  Bedroom2       13580 non-null  float64
 11  Bathroom       13580 non-null  float64
 12  Car            13518 non-null  float64
 13  Landsize       13580 non-null  float64
 14  BuildingArea   7130 non-null   float64
 15  YearBuilt      8205 non-null   float64
 16  CouncilArea    12211 non-null  object
 17  Lattitude      13580 non-null  float64
 18  Longtitude     13580 non-null  float64
 19  Regionname     13580 non-null  object
 20  Propertycount  13580 non-null  float64
dtypes: float64(12), int64(1), object(8)
memory usage: 2.2+ MB

In [125]:
# select data to model with - print columns first
melbourne_data.columns

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea', 'Lattitude',
       'Longtitude', 'Regionname', 'Propertycount'],
      dtype='object')

In [126]:
y = melbourne_data.Price # our target - what we try to predict
x = melbourne_data.drop(['Price'], axis=1) # all features except price (our predictor)

In [127]:
x.head() # features that will be used in our model to predict

,Suburb,Address,Rooms,Type,Method,SellerG,Date,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,S,Biggin,3/12/2016,2.5,3067.0,2.0,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,S,Biggin,4/02/2016,2.5,3067.0,2.0,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,SP,Biggin,4/03/2017,2.5,3067.0,3.0,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,PI,Biggin,4/03/2017,2.5,3067.0,3.0,2.0,1.0,94.0,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,VB,Nelson,4/06/2016,2.5,3067.0,3.0,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0

In [128]:
y.head() # house prices

0    1480000.0
1    1035000.0
2    1465000.0
3     850000.0
4    1600000.0
Name: Price, dtype: float64

In [129]:
x.describe()

,Rooms,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
count,13580.000000,13580.000000,13580.000000,13580.000000,13580.000000,13518.000000,13580.000000,7130.000000,8205.000000,13580.000000,13580.000000,13580.000000
mean,2.937997,10.137776,3105.301915,2.914728,1.534242,1.610075,558.416127,151.967650,1964.684217,-37.809203,144.995216,7454.417378
std,0.955748,5.868725,90.676964,0.965921,0.691712,0.962634,3990.669241,541.014538,37.273762,0.079260,0.103916,4378.581772
min,1.000000,0.000000,3000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1196.000000,-38.182550,144.431810,249.000000
25%,2.000000,6.100000,3044.000000,2.000000,1.000000,1.000000,177.000000,93.000000,1940.000000,-37.856822,144.929600,4380.000000
50%,3.000000,9.200000,3084.000000,3.000000,1.000000,2.000000,440.000000,126.000000,1970.000000,-37.802355,145.000100,6555.000000
75%,3.000000,13.000000,3148.000000,3.000000,2.000000,2.000000,651.000000,174.000000,1999.000000,-37.756400,145.058305,10331.000000
max,10.000000,48.100000,3977.000000,20.000000,8.000000,10.000000,433014.000000,44515.000000,2018.000000,-37.408530,145.526350,21650.000000

In [130]:
y.describe()

count    1.358000e+04
mean     1.075684e+06
std      6.393107e+05
min      8.500000e+04
25%      6.500000e+05
50%      9.030000e+05
75%      1.330000e+06
max      9.000000e+06
Name: Price, dtype: float64

In [131]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=18)

In [132]:
from sklearn.metrics import mean_absolute_error
from sklearn.ensemble import RandomForestRegressor
def finetune_return_mae(x_train, x_test, y_train, y_test):
    finetuned_model = RandomForestRegressor(n_estimators=100, random_state=18)
    finetuned_model.fit(x_train, y_train)
    y_predicted_values = finetuned_model.predict(x_test)
    mae = mean_absolute_error(y_test, y_predicted_values)
    return mae

In [133]:
columns_with_missing_values = []
for column in x_train.columns:
    if x_train[column].isnull().any():
        columns_with_missing_values.append(column)
x_train.drop(columns_with_missing_values, axis=1, inplace=True)
x_test.drop(columns_with_missing_values, axis=1, inplace=True)

## Handling Categorical variables

In [134]:
# cardinality means number of unique values in a column
low_cardinality_columns = []
for column in x_train.columns:
    if x_train[column].nunique() < 10 and x_train[column].dtype == "object":
        low_cardinality_columns.append(column)
# adds columns with unique number values less than 10

In [135]:
numerical_columns = []
for column in x_train.columns:
    if x_train[column].dtype in ['float64', 'int64']:
        numerical_columns.append(column)

In [136]:
# combine only these two types of data in our data
data = low_cardinality_columns + numerical_columns
x_train = x_train[data].copy()
x_test = x_test[data].copy()

In [137]:
x_train.head()

,Type,Method,Regionname,Rooms,Distance,Postcode,Bedroom2,Bathroom,Landsize,Lattitude,Longtitude,Propertycount
2454,u,SP,Western Metropolitan,2,8.0,3040.0,2.0,1.0,170.0,-37.74750,144.89590,9264.0
13030,h,S,Eastern Victoria,3,31.6,3796.0,3.0,1.0,915.0,-37.78495,145.39190,3532.0
5490,h,PI,Western Metropolitan,3,6.6,3011.0,3.0,3.0,227.0,-37.80330,144.88970,2417.0
2796,h,PI,Southern Metropolitan,5,9.2,3146.0,5.0,3.0,696.0,-37.85630,145.07090,10412.0
12271,h,S,Eastern Metropolitan,3,23.0,3136.0,3.0,2.0,1007.0,-37.76653,145.29163,2985.0

In [138]:
# Get the list of these categorical variables
categorical_variables_names = (x_train.dtypes == 'object') # selects the other data type
categorical_variables_names = list(categorical_variables_names[categorical_variables_names].index)
categorical_variables_names

['Type', 'Method', 'Regionname']

Approach 1: Drop the categorical columns if they are not useful

In [139]:
x_train_drop_categorical_columns = x_train.select_dtypes(exclude=['object'])
x_test_drop_categorical_columns = x_test.select_dtypes(exclude=['object'])
print("Approach 1: Dropping these categorical columns")
finetune_return_mae(x_train_drop_categorical_columns, x_test_drop_categorical_columns, y_train, y_test)

Approach 1: Dropping these categorical columns

180711.54493951186

Approach 2: Ordinal Encoding - Assigns each value to a different integer, with ordered values e.g worst, bad, ok, good, best - 0, 1, 2, 3, 4, 5. Works best for tree-based models like random forest and decision tree

In [140]:
from sklearn.preprocessing import OrdinalEncoder

OE_x_train = x_train.copy()
OE_x_test = x_test.copy()
OE = OrdinalEncoder()

OE_x_train[categorical_variables_names] = OE.fit_transform(OE_x_train[categorical_variables_names])
OE_x_test[categorical_variables_names] = OE.transform(OE_x_test[categorical_variables_names])

print("Approach 2: Ordinal Encoding")
finetune_return_mae(OE_x_train, OE_x_test, y_train, y_test)

Approach 2: Ordinal Encoding

169525.82188757978

Approach 3: One-hot Encoding - Creates new columns that indicates presence or absence of these variables e.g column for variable red, with 0/1 for presence/absence and additional columns for other colors. It works best for nominal variables such as colors, which values have no ranking

In [141]:
from sklearn.preprocessing import OneHotEncoder

OHE = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

OHE_x_train = pd.DataFrame(OHE.fit_transform(x_train[categorical_variables_names]))
OHE_x_test = pd.DataFrame(OHE.transform(x_test[categorical_variables_names]))

OHE_x_train.index = x_train.index
OHE_x_test.index = x_test.index

numerical_x_train = x_train.drop(categorical_variables_names, axis=1)
numerical_x_test = x_test.drop(categorical_variables_names, axis=1)

OHE_x_train = pd.concat([OHE_x_train, numerical_x_train], axis=1)
OHE_x_test = pd.concat([OHE_x_test, numerical_x_test], axis=1)

OHE_x_train.columns = OHE_x_train.columns.astype(str)
OHE_x_test.columns = OHE_x_test.columns.astype(str)

print("Approach 3: OneHotEncoder")
finetune_return_mae(OHE_x_train,OHE_x_test,y_train,y_test)

Approach 3: OneHotEncoder

170206.73373413284

The best approach is Approach 2 using Ordinal Encoding. The worst was the first approach; removing the columns with categorical data. Approach 2 and Approach 3 had very similar MAE scores.

In [142]:
from sklearn.ensemble import RandomForestRegressor
melbourne_model = RandomForestRegressor(n_estimators=100, random_state=18) # random state is like seeding, to permit reproducibility
# n_estimators=100
melbourne_model.fit(OE_x_train,y_train) # fitting model with data

RandomForestRegressor(random_state=18)

In [143]:
# Here, we predict house price using the train and test data on the model
y_train_pred = melbourne_model.predict(OE_x_train)
y_test_pred = melbourne_model.predict(OE_x_test)

In [144]:
from sklearn.metrics import r2_score
# here we can assess the r2 score of the model to check reliability and accuracy of the model, against exposed and unexposed data
r2_score_train = r2_score(y_train, y_train_pred)
r2_score_test = r2_score(y_test, y_test_pred)

In [145]:
r2_score_train

0.9700231109144637

In [146]:
r2_score_test

0.7845173038885697

In [147]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error_prediction_vs_actual = mean_absolute_error(y_test,y_test_pred)
mean_absolute_error_prediction_vs_actual

169525.82188757978

In [148]:
# Testing Model
print("We can predict Houses with the following characteristics:\n\n", x_test.head())

We can predict Houses with the following characteristics:

       Type Method             Regionname  Rooms  Distance  Postcode  Bedroom2  \
6675     h      S   Western Metropolitan      3       7.0    3013.0       2.0
11613    h     SP  Northern Metropolitan      4      12.1    3083.0       4.0
8813     t      S   Eastern Metropolitan      3      15.4    3131.0       3.0
3150     u      S  Southern Metropolitan      2       4.6    3122.0       2.0
8729     h     PI  Southern Metropolitan      4       7.9    3103.0       4.0

       Bathroom  Landsize  Lattitude  Longtitude  Propertycount
6675        1.0     446.0  -37.81830   144.86660         6543.0
11613       1.0     535.0  -37.69847   145.06010        10175.0
8813        2.0     353.0  -37.83401   145.17757         4385.0
3150        1.0       0.0  -37.83430   145.03640        11308.0
8729        3.0     380.0  -37.80156   145.06715         5682.0

In [149]:
y_test_pred

array([ 916440.,  767595.,  953260., ..., 1788440.,  389380.,  392485.])

In [150]:
y_test

6675      681000.0
11613     800000.0
8813      850500.0
3150      655000.0
8729     1475000.0
           ...
8010     1060000.0
11699     500000.0
81       1850000.0
5140      323000.0
2317      313000.0
Name: Price, Length: 2716, dtype: float64